version: '3'


#zookeeper,kafka,orderer,ca均只使用一个，因为单机版只是一个样例
services:

  peer0.org1.workflow.com:
    container_name: peer0.org1.workflow.com
    image: workflow-peer:2.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false 
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_MSP_ADMINCERTS=/etc/hyperledger/crypto/admin/msp/signcerts/Admin@org1.workflow.com-cert.pem
      - CORE_PEER_MSP_KEYSTORE=/etc/hyperledger/crypto/admin/msp/keystore/4d77cfd12a41398d4ed722a7448344ed2a2ea93cc8166a44578b35a2376292cc_sk
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.workflow.com
      - CORE_PEER_ID=peer0.org1.workflow.com
      - CORE_PEER_ADDRESS=peer0.org1.workflow.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.workflow.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.workflow.com:7051
      - ORDERER_TLS_PATH=/etc/hyperledger/crypto/orderer/tls/ca.crt
      - FABRIC_ORDERER_ADDR=grpcs://orderer.workflow.com:7050
      - FABRIC_ORDERER_NAME=orderer.workflow.com
      - FABRIC_USERNAME=Jim
      - WF_FLUSHTIME=200
      - WF_CHECKTIME=500
      - WF_CHECKROUND=20
      - WF_ACTIVITIPORT=8888
      - WF_AUTOTEST=false
      - MONITOR_CONFIG=/etc/hyperledger/crypto/channelConfig/monitorIps.txt
      - WORKFLOWCHANNEL_PEER_CONFIG=/etc/hyperledger/crypto/channelConfig/channelPeerConfig.txt
      - WORKFLOWCHANNEL_ORDERER_CONFIG=/etc/hyperledger/crypto/channelConfig/channelOrdererConfig.txt
      - isEvil=false
      - cacheCleanTime=3600000
      - SERVICE_RESULT_PERSISTENCE=false
      - DB_URL=jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
      - DB_USER=root
      - DB_PASSWORD=123456
      - NACOS_ADDRESS=peer0.org1.workflow.com
      - NACOS_PORT=8848
    ports:
      - 7051:7051
      - 7053:7053
      - 8999:8999
      - 8888:8888
      - 7848:8848
    command: sh -c "/usr/local/scripts/cmd.sh"
    volumes:
      - ./sdk-application/artifacts/channel/channelConfig:/etc/hyperledger/crypto/channelConfig
      - ./sdk-application/artifacts/channel/crypto-config/peerOrganizations/org1.workflow.com/peers/peer0.org1.workflow.com/:/etc/hyperledger/crypto/peer
      - ./sdk-application/artifacts/channel/crypto-config/peerOrganizations/org1.workflow.com/users/Admin@org1.workflow.com/:/etc/hyperledger/crypto/admin
      - ./sdk-application/artifacts/channel/crypto-config/ordererOrganizations/workflow.com/orderers/orderer.workflow.com/:/etc/hyperledger/crypto/orderer
      - ./volumes/codes/wfService/target/wfService.jar:/usr/local/monitor/wfService.jar
      - ./volumes/codes/wfEngine/target/wfEngine.jar:/usr/local/wfEngine.jar
      - ./volumes/scripts:/usr/local/scripts
      - ./volumes/config/swarm.key:/root/swarm.key
      - ./sdk-application/artifacts/channel/crypto-config/peerOrganizations:/etc/hyperledger/crypto/allPeers
      - ./sdk-application/artifacts/channel/crypto-config/ordererOrganizations:/etc/hyperledger/crypto/allOrderers
      - ./volumes/config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./volumes/lib/peer:/usr/local/bin/peer
      - ./volumes/codes/nacos/distribution/target/nacos-server-1.2.0-SNAPSHOT/nacos:/nacos

