// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rwSetList.proto

package org.activiti.engine.impl.db.workflowClass.proto.rwSet;

public final class rwSetList {
  private rwSetList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface rwSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.rwSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    boolean hasReadSet();
    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getReadSet();
    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder getReadSetOrBuilder();

    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    boolean hasWriteSet();
    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getWriteSet();
    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder getWriteSetOrBuilder();
  }
  /**
   * Protobuf type {@code protos.rwSet}
   */
  public  static final class rwSet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.rwSet)
      rwSetOrBuilder {
    // Use rwSet.newBuilder() to construct.
    private rwSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private rwSet() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private rwSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder subBuilder = null;
              if (readSet_ != null) {
                subBuilder = readSet_.toBuilder();
              }
              readSet_ = input.readMessage(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(readSet_);
                readSet_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder subBuilder = null;
              if (writeSet_ != null) {
                subBuilder = writeSet_.toBuilder();
              }
              writeSet_ = input.readMessage(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(writeSet_);
                writeSet_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_rwSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_rwSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.Builder.class);
    }

    public static final int READSET_FIELD_NUMBER = 1;
    private org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet readSet_;
    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    public boolean hasReadSet() {
      return readSet_ != null;
    }
    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getReadSet() {
      return readSet_ == null ? org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.getDefaultInstance() : readSet_;
    }
    /**
     * <code>optional .protos.readSet readSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder getReadSetOrBuilder() {
      return getReadSet();
    }

    public static final int WRITESET_FIELD_NUMBER = 2;
    private org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet writeSet_;
    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    public boolean hasWriteSet() {
      return writeSet_ != null;
    }
    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getWriteSet() {
      return writeSet_ == null ? org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.getDefaultInstance() : writeSet_;
    }
    /**
     * <code>optional .protos.writeSet writeSet = 2;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder getWriteSetOrBuilder() {
      return getWriteSet();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (readSet_ != null) {
        output.writeMessage(1, getReadSet());
      }
      if (writeSet_ != null) {
        output.writeMessage(2, getWriteSet());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (readSet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReadSet());
      }
      if (writeSet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWriteSet());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet)) {
        return super.equals(obj);
      }
      org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet other = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet) obj;

      boolean result = true;
      result = result && (hasReadSet() == other.hasReadSet());
      if (hasReadSet()) {
        result = result && getReadSet()
            .equals(other.getReadSet());
      }
      result = result && (hasWriteSet() == other.hasWriteSet());
      if (hasWriteSet()) {
        result = result && getWriteSet()
            .equals(other.getWriteSet());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasReadSet()) {
        hash = (37 * hash) + READSET_FIELD_NUMBER;
        hash = (53 * hash) + getReadSet().hashCode();
      }
      if (hasWriteSet()) {
        hash = (37 * hash) + WRITESET_FIELD_NUMBER;
        hash = (53 * hash) + getWriteSet().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.rwSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.rwSet)
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_rwSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_rwSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.Builder.class);
      }

      // Construct using org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (readSetBuilder_ == null) {
          readSet_ = null;
        } else {
          readSet_ = null;
          readSetBuilder_ = null;
        }
        if (writeSetBuilder_ == null) {
          writeSet_ = null;
        } else {
          writeSet_ = null;
          writeSetBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_rwSet_descriptor;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet getDefaultInstanceForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.getDefaultInstance();
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet build() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet buildPartial() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet result = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet(this);
        if (readSetBuilder_ == null) {
          result.readSet_ = readSet_;
        } else {
          result.readSet_ = readSetBuilder_.build();
        }
        if (writeSetBuilder_ == null) {
          result.writeSet_ = writeSet_;
        } else {
          result.writeSet_ = writeSetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet) {
          return mergeFrom((org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet other) {
        if (other == org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet.getDefaultInstance()) return this;
        if (other.hasReadSet()) {
          mergeReadSet(other.getReadSet());
        }
        if (other.hasWriteSet()) {
          mergeWriteSet(other.getWriteSet());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet readSet_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder> readSetBuilder_;
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public boolean hasReadSet() {
        return readSetBuilder_ != null || readSet_ != null;
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getReadSet() {
        if (readSetBuilder_ == null) {
          return readSet_ == null ? org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.getDefaultInstance() : readSet_;
        } else {
          return readSetBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public Builder setReadSet(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet value) {
        if (readSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readSet_ = value;
          onChanged();
        } else {
          readSetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public Builder setReadSet(
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder builderForValue) {
        if (readSetBuilder_ == null) {
          readSet_ = builderForValue.build();
          onChanged();
        } else {
          readSetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public Builder mergeReadSet(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet value) {
        if (readSetBuilder_ == null) {
          if (readSet_ != null) {
            readSet_ =
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.newBuilder(readSet_).mergeFrom(value).buildPartial();
          } else {
            readSet_ = value;
          }
          onChanged();
        } else {
          readSetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public Builder clearReadSet() {
        if (readSetBuilder_ == null) {
          readSet_ = null;
          onChanged();
        } else {
          readSet_ = null;
          readSetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder getReadSetBuilder() {
        
        onChanged();
        return getReadSetFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder getReadSetOrBuilder() {
        if (readSetBuilder_ != null) {
          return readSetBuilder_.getMessageOrBuilder();
        } else {
          return readSet_ == null ?
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.getDefaultInstance() : readSet_;
        }
      }
      /**
       * <code>optional .protos.readSet readSet = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder> 
          getReadSetFieldBuilder() {
        if (readSetBuilder_ == null) {
          readSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder>(
                  getReadSet(),
                  getParentForChildren(),
                  isClean());
          readSet_ = null;
        }
        return readSetBuilder_;
      }

      private org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet writeSet_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder> writeSetBuilder_;
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public boolean hasWriteSet() {
        return writeSetBuilder_ != null || writeSet_ != null;
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getWriteSet() {
        if (writeSetBuilder_ == null) {
          return writeSet_ == null ? org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.getDefaultInstance() : writeSet_;
        } else {
          return writeSetBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public Builder setWriteSet(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet value) {
        if (writeSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          writeSet_ = value;
          onChanged();
        } else {
          writeSetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public Builder setWriteSet(
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder builderForValue) {
        if (writeSetBuilder_ == null) {
          writeSet_ = builderForValue.build();
          onChanged();
        } else {
          writeSetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public Builder mergeWriteSet(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet value) {
        if (writeSetBuilder_ == null) {
          if (writeSet_ != null) {
            writeSet_ =
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.newBuilder(writeSet_).mergeFrom(value).buildPartial();
          } else {
            writeSet_ = value;
          }
          onChanged();
        } else {
          writeSetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public Builder clearWriteSet() {
        if (writeSetBuilder_ == null) {
          writeSet_ = null;
          onChanged();
        } else {
          writeSet_ = null;
          writeSetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder getWriteSetBuilder() {
        
        onChanged();
        return getWriteSetFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder getWriteSetOrBuilder() {
        if (writeSetBuilder_ != null) {
          return writeSetBuilder_.getMessageOrBuilder();
        } else {
          return writeSet_ == null ?
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.getDefaultInstance() : writeSet_;
        }
      }
      /**
       * <code>optional .protos.writeSet writeSet = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder> 
          getWriteSetFieldBuilder() {
        if (writeSetBuilder_ == null) {
          writeSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder>(
                  getWriteSet(),
                  getParentForChildren(),
                  isClean());
          writeSet_ = null;
        }
        return writeSetBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.rwSet)
    }

    // @@protoc_insertion_point(class_scope:protos.rwSet)
    private static final org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet();
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<rwSet>
        PARSER = new com.google.protobuf.AbstractParser<rwSet>() {
      public rwSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new rwSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<rwSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<rwSet> getParserForType() {
      return PARSER;
    }

    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.rwSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface readSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.readSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> 
        getReadSetList();
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getReadSet(int index);
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    int getReadSetCount();
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
        getReadSetOrBuilderList();
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getReadSetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.readSet}
   */
  public  static final class readSet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.readSet)
      readSetOrBuilder {
    // Use readSet.newBuilder() to construct.
    private readSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private readSet() {
      readSet_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private readSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                readSet_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity>();
                mutable_bitField0_ |= 0x00000001;
              }
              readSet_.add(
                  input.readMessage(org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          readSet_ = java.util.Collections.unmodifiableList(readSet_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_readSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_readSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder.class);
    }

    public static final int READSET_FIELD_NUMBER = 1;
    private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> readSet_;
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> getReadSetList() {
      return readSet_;
    }
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
        getReadSetOrBuilderList() {
      return readSet_;
    }
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    public int getReadSetCount() {
      return readSet_.size();
    }
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getReadSet(int index) {
      return readSet_.get(index);
    }
    /**
     * <code>repeated .protos.entity readSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getReadSetOrBuilder(
        int index) {
      return readSet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < readSet_.size(); i++) {
        output.writeMessage(1, readSet_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < readSet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, readSet_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet)) {
        return super.equals(obj);
      }
      org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet other = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet) obj;

      boolean result = true;
      result = result && getReadSetList()
          .equals(other.getReadSetList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getReadSetCount() > 0) {
        hash = (37 * hash) + READSET_FIELD_NUMBER;
        hash = (53 * hash) + getReadSetList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.readSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.readSet)
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_readSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_readSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.Builder.class);
      }

      // Construct using org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReadSetFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (readSetBuilder_ == null) {
          readSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          readSetBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_readSet_descriptor;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getDefaultInstanceForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.getDefaultInstance();
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet build() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet buildPartial() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet result = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet(this);
        int from_bitField0_ = bitField0_;
        if (readSetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            readSet_ = java.util.Collections.unmodifiableList(readSet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.readSet_ = readSet_;
        } else {
          result.readSet_ = readSetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet) {
          return mergeFrom((org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet other) {
        if (other == org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet.getDefaultInstance()) return this;
        if (readSetBuilder_ == null) {
          if (!other.readSet_.isEmpty()) {
            if (readSet_.isEmpty()) {
              readSet_ = other.readSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReadSetIsMutable();
              readSet_.addAll(other.readSet_);
            }
            onChanged();
          }
        } else {
          if (!other.readSet_.isEmpty()) {
            if (readSetBuilder_.isEmpty()) {
              readSetBuilder_.dispose();
              readSetBuilder_ = null;
              readSet_ = other.readSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              readSetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReadSetFieldBuilder() : null;
            } else {
              readSetBuilder_.addAllMessages(other.readSet_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> readSet_ =
        java.util.Collections.emptyList();
      private void ensureReadSetIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          readSet_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity>(readSet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> readSetBuilder_;

      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> getReadSetList() {
        if (readSetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(readSet_);
        } else {
          return readSetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public int getReadSetCount() {
        if (readSetBuilder_ == null) {
          return readSet_.size();
        } else {
          return readSetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getReadSet(int index) {
        if (readSetBuilder_ == null) {
          return readSet_.get(index);
        } else {
          return readSetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder setReadSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (readSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadSetIsMutable();
          readSet_.set(index, value);
          onChanged();
        } else {
          readSetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder setReadSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (readSetBuilder_ == null) {
          ensureReadSetIsMutable();
          readSet_.set(index, builderForValue.build());
          onChanged();
        } else {
          readSetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder addReadSet(org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (readSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadSetIsMutable();
          readSet_.add(value);
          onChanged();
        } else {
          readSetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder addReadSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (readSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadSetIsMutable();
          readSet_.add(index, value);
          onChanged();
        } else {
          readSetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder addReadSet(
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (readSetBuilder_ == null) {
          ensureReadSetIsMutable();
          readSet_.add(builderForValue.build());
          onChanged();
        } else {
          readSetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder addReadSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (readSetBuilder_ == null) {
          ensureReadSetIsMutable();
          readSet_.add(index, builderForValue.build());
          onChanged();
        } else {
          readSetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder addAllReadSet(
          java.lang.Iterable<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> values) {
        if (readSetBuilder_ == null) {
          ensureReadSetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, readSet_);
          onChanged();
        } else {
          readSetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder clearReadSet() {
        if (readSetBuilder_ == null) {
          readSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          readSetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public Builder removeReadSet(int index) {
        if (readSetBuilder_ == null) {
          ensureReadSetIsMutable();
          readSet_.remove(index);
          onChanged();
        } else {
          readSetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder getReadSetBuilder(
          int index) {
        return getReadSetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getReadSetOrBuilder(
          int index) {
        if (readSetBuilder_ == null) {
          return readSet_.get(index);  } else {
          return readSetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
           getReadSetOrBuilderList() {
        if (readSetBuilder_ != null) {
          return readSetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(readSet_);
        }
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder addReadSetBuilder() {
        return getReadSetFieldBuilder().addBuilder(
            org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder addReadSetBuilder(
          int index) {
        return getReadSetFieldBuilder().addBuilder(
            index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.entity readSet = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder> 
           getReadSetBuilderList() {
        return getReadSetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
          getReadSetFieldBuilder() {
        if (readSetBuilder_ == null) {
          readSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder>(
                  readSet_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          readSet_ = null;
        }
        return readSetBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.readSet)
    }

    // @@protoc_insertion_point(class_scope:protos.readSet)
    private static final org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet();
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<readSet>
        PARSER = new com.google.protobuf.AbstractParser<readSet>() {
      public readSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new readSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<readSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<readSet> getParserForType() {
      return PARSER;
    }

    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.readSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface writeSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.writeSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> 
        getWriteSetList();
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getWriteSet(int index);
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    int getWriteSetCount();
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
        getWriteSetOrBuilderList();
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getWriteSetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.writeSet}
   */
  public  static final class writeSet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.writeSet)
      writeSetOrBuilder {
    // Use writeSet.newBuilder() to construct.
    private writeSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private writeSet() {
      writeSet_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private writeSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                writeSet_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity>();
                mutable_bitField0_ |= 0x00000001;
              }
              writeSet_.add(
                  input.readMessage(org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          writeSet_ = java.util.Collections.unmodifiableList(writeSet_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_writeSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_writeSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder.class);
    }

    public static final int WRITESET_FIELD_NUMBER = 1;
    private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> writeSet_;
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> getWriteSetList() {
      return writeSet_;
    }
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
        getWriteSetOrBuilderList() {
      return writeSet_;
    }
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    public int getWriteSetCount() {
      return writeSet_.size();
    }
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getWriteSet(int index) {
      return writeSet_.get(index);
    }
    /**
     * <code>repeated .protos.entity writeSet = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getWriteSetOrBuilder(
        int index) {
      return writeSet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < writeSet_.size(); i++) {
        output.writeMessage(1, writeSet_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < writeSet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, writeSet_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet)) {
        return super.equals(obj);
      }
      org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet other = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet) obj;

      boolean result = true;
      result = result && getWriteSetList()
          .equals(other.getWriteSetList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getWriteSetCount() > 0) {
        hash = (37 * hash) + WRITESET_FIELD_NUMBER;
        hash = (53 * hash) + getWriteSetList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.writeSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.writeSet)
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_writeSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_writeSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.class, org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.Builder.class);
      }

      // Construct using org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWriteSetFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (writeSetBuilder_ == null) {
          writeSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          writeSetBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.internal_static_protos_writeSet_descriptor;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getDefaultInstanceForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.getDefaultInstance();
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet build() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet buildPartial() {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet result = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet(this);
        int from_bitField0_ = bitField0_;
        if (writeSetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            writeSet_ = java.util.Collections.unmodifiableList(writeSet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.writeSet_ = writeSet_;
        } else {
          result.writeSet_ = writeSetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet) {
          return mergeFrom((org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet other) {
        if (other == org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet.getDefaultInstance()) return this;
        if (writeSetBuilder_ == null) {
          if (!other.writeSet_.isEmpty()) {
            if (writeSet_.isEmpty()) {
              writeSet_ = other.writeSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWriteSetIsMutable();
              writeSet_.addAll(other.writeSet_);
            }
            onChanged();
          }
        } else {
          if (!other.writeSet_.isEmpty()) {
            if (writeSetBuilder_.isEmpty()) {
              writeSetBuilder_.dispose();
              writeSetBuilder_ = null;
              writeSet_ = other.writeSet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              writeSetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWriteSetFieldBuilder() : null;
            } else {
              writeSetBuilder_.addAllMessages(other.writeSet_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> writeSet_ =
        java.util.Collections.emptyList();
      private void ensureWriteSetIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          writeSet_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity>(writeSet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> writeSetBuilder_;

      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> getWriteSetList() {
        if (writeSetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(writeSet_);
        } else {
          return writeSetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public int getWriteSetCount() {
        if (writeSetBuilder_ == null) {
          return writeSet_.size();
        } else {
          return writeSetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity getWriteSet(int index) {
        if (writeSetBuilder_ == null) {
          return writeSet_.get(index);
        } else {
          return writeSetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder setWriteSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (writeSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteSetIsMutable();
          writeSet_.set(index, value);
          onChanged();
        } else {
          writeSetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder setWriteSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (writeSetBuilder_ == null) {
          ensureWriteSetIsMutable();
          writeSet_.set(index, builderForValue.build());
          onChanged();
        } else {
          writeSetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder addWriteSet(org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (writeSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteSetIsMutable();
          writeSet_.add(value);
          onChanged();
        } else {
          writeSetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder addWriteSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity value) {
        if (writeSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteSetIsMutable();
          writeSet_.add(index, value);
          onChanged();
        } else {
          writeSetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder addWriteSet(
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (writeSetBuilder_ == null) {
          ensureWriteSetIsMutable();
          writeSet_.add(builderForValue.build());
          onChanged();
        } else {
          writeSetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder addWriteSet(
          int index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder builderForValue) {
        if (writeSetBuilder_ == null) {
          ensureWriteSetIsMutable();
          writeSet_.add(index, builderForValue.build());
          onChanged();
        } else {
          writeSetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder addAllWriteSet(
          java.lang.Iterable<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity> values) {
        if (writeSetBuilder_ == null) {
          ensureWriteSetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, writeSet_);
          onChanged();
        } else {
          writeSetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder clearWriteSet() {
        if (writeSetBuilder_ == null) {
          writeSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          writeSetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public Builder removeWriteSet(int index) {
        if (writeSetBuilder_ == null) {
          ensureWriteSetIsMutable();
          writeSet_.remove(index);
          onChanged();
        } else {
          writeSetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder getWriteSetBuilder(
          int index) {
        return getWriteSetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder getWriteSetOrBuilder(
          int index) {
        if (writeSetBuilder_ == null) {
          return writeSet_.get(index);  } else {
          return writeSetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
           getWriteSetOrBuilderList() {
        if (writeSetBuilder_ != null) {
          return writeSetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(writeSet_);
        }
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder addWriteSetBuilder() {
        return getWriteSetFieldBuilder().addBuilder(
            org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder addWriteSetBuilder(
          int index) {
        return getWriteSetFieldBuilder().addBuilder(
            index, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.entity writeSet = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder> 
           getWriteSetBuilderList() {
        return getWriteSetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder> 
          getWriteSetFieldBuilder() {
        if (writeSetBuilder_ == null) {
          writeSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entity.Builder, org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.entityOrBuilder>(
                  writeSet_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          writeSet_ = null;
        }
        return writeSetBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.writeSet)
    }

    // @@protoc_insertion_point(class_scope:protos.writeSet)
    private static final org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet();
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<writeSet>
        PARSER = new com.google.protobuf.AbstractParser<writeSet>() {
      public writeSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new writeSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<writeSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<writeSet> getParserForType() {
      return PARSER;
    }

    public org.activiti.engine.impl.db.workflowClass.proto.rwSet.rwSetList.writeSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_rwSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_rwSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_readSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_readSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_writeSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_writeSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017rwSetList.proto\022\006protos\032\022simpleEntity." +
      "proto\"M\n\005rwSet\022 \n\007readSet\030\001 \001(\0132\017.protos" +
      ".readSet\022\"\n\010writeSet\030\002 \001(\0132\020.protos.writ" +
      "eSet\"*\n\007readSet\022\037\n\007readSet\030\001 \003(\0132\016.proto" +
      "s.entity\",\n\010writeSet\022 \n\010writeSet\030\001 \003(\0132\016" +
      ".protos.entityBB\n5org.activiti.engine.im" +
      "pl.db.workflowClass.proto.rwSetB\trwSetLi" +
      "stb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.getDescriptor(),
        }, assigner);
    internal_static_protos_rwSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_rwSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_rwSet_descriptor,
        new java.lang.String[] { "ReadSet", "WriteSet", });
    internal_static_protos_readSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_readSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_readSet_descriptor,
        new java.lang.String[] { "ReadSet", });
    internal_static_protos_writeSet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_writeSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_writeSet_descriptor,
        new java.lang.String[] { "WriteSet", });
    org.activiti.engine.impl.db.workflowClass.proto.entity.simpleEntity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
