// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bigPackage.proto

package org.activiti.engine.impl.db.workflowClass.proto.bigPackage;

public final class wfPackage {
  private wfPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface wfTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.wfTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string rwSet = 1;</code>
     */
    java.lang.String getRwSet();
    /**
     * <code>optional string rwSet = 1;</code>
     */
    com.google.protobuf.ByteString
        getRwSetBytes();

    /**
     * <code>optional string businessData = 2;</code>
     */
    java.lang.String getBusinessData();
    /**
     * <code>optional string businessData = 2;</code>
     */
    com.google.protobuf.ByteString
        getBusinessDataBytes();

    /**
     * <code>optional string serviceResultJson = 3;</code>
     */
    java.lang.String getServiceResultJson();
    /**
     * <code>optional string serviceResultJson = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceResultJsonBytes();

    /**
     * <code>optional string oid = 4;</code>
     */
    java.lang.String getOid();
    /**
     * <code>optional string oid = 4;</code>
     */
    com.google.protobuf.ByteString
        getOidBytes();
  }
  /**
   * Protobuf type {@code protos.wfTransaction}
   */
  public  static final class wfTransaction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.wfTransaction)
      wfTransactionOrBuilder {
    // Use wfTransaction.newBuilder() to construct.
    private wfTransaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private wfTransaction() {
      rwSet_ = "";
      businessData_ = "";
      serviceResultJson_ = "";
      oid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private wfTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              rwSet_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              businessData_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceResultJson_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              oid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_wfTransaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_wfTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.class, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder.class);
    }

    public static final int RWSET_FIELD_NUMBER = 1;
    private volatile java.lang.Object rwSet_;
    /**
     * <code>optional string rwSet = 1;</code>
     */
    public java.lang.String getRwSet() {
      java.lang.Object ref = rwSet_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rwSet_ = s;
        return s;
      }
    }
    /**
     * <code>optional string rwSet = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRwSetBytes() {
      java.lang.Object ref = rwSet_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rwSet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUSINESSDATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object businessData_;
    /**
     * <code>optional string businessData = 2;</code>
     */
    public java.lang.String getBusinessData() {
      java.lang.Object ref = businessData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        businessData_ = s;
        return s;
      }
    }
    /**
     * <code>optional string businessData = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBusinessDataBytes() {
      java.lang.Object ref = businessData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        businessData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICERESULTJSON_FIELD_NUMBER = 3;
    private volatile java.lang.Object serviceResultJson_;
    /**
     * <code>optional string serviceResultJson = 3;</code>
     */
    public java.lang.String getServiceResultJson() {
      java.lang.Object ref = serviceResultJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceResultJson_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serviceResultJson = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceResultJsonBytes() {
      java.lang.Object ref = serviceResultJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceResultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OID_FIELD_NUMBER = 4;
    private volatile java.lang.Object oid_;
    /**
     * <code>optional string oid = 4;</code>
     */
    public java.lang.String getOid() {
      java.lang.Object ref = oid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string oid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOidBytes() {
      java.lang.Object ref = oid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRwSetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, rwSet_);
      }
      if (!getBusinessDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, businessData_);
      }
      if (!getServiceResultJsonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, serviceResultJson_);
      }
      if (!getOidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, oid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRwSetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, rwSet_);
      }
      if (!getBusinessDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, businessData_);
      }
      if (!getServiceResultJsonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, serviceResultJson_);
      }
      if (!getOidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, oid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction)) {
        return super.equals(obj);
      }
      org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction other = (org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction) obj;

      boolean result = true;
      result = result && getRwSet()
          .equals(other.getRwSet());
      result = result && getBusinessData()
          .equals(other.getBusinessData());
      result = result && getServiceResultJson()
          .equals(other.getServiceResultJson());
      result = result && getOid()
          .equals(other.getOid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RWSET_FIELD_NUMBER;
      hash = (53 * hash) + getRwSet().hashCode();
      hash = (37 * hash) + BUSINESSDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessData().hashCode();
      hash = (37 * hash) + SERVICERESULTJSON_FIELD_NUMBER;
      hash = (53 * hash) + getServiceResultJson().hashCode();
      hash = (37 * hash) + OID_FIELD_NUMBER;
      hash = (53 * hash) + getOid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.wfTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.wfTransaction)
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_wfTransaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_wfTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.class, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder.class);
      }

      // Construct using org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rwSet_ = "";

        businessData_ = "";

        serviceResultJson_ = "";

        oid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_wfTransaction_descriptor;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getDefaultInstanceForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.getDefaultInstance();
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction build() {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction buildPartial() {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction result = new org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction(this);
        result.rwSet_ = rwSet_;
        result.businessData_ = businessData_;
        result.serviceResultJson_ = serviceResultJson_;
        result.oid_ = oid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction) {
          return mergeFrom((org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction other) {
        if (other == org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.getDefaultInstance()) return this;
        if (!other.getRwSet().isEmpty()) {
          rwSet_ = other.rwSet_;
          onChanged();
        }
        if (!other.getBusinessData().isEmpty()) {
          businessData_ = other.businessData_;
          onChanged();
        }
        if (!other.getServiceResultJson().isEmpty()) {
          serviceResultJson_ = other.serviceResultJson_;
          onChanged();
        }
        if (!other.getOid().isEmpty()) {
          oid_ = other.oid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object rwSet_ = "";
      /**
       * <code>optional string rwSet = 1;</code>
       */
      public java.lang.String getRwSet() {
        java.lang.Object ref = rwSet_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rwSet_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rwSet = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRwSetBytes() {
        java.lang.Object ref = rwSet_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rwSet_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rwSet = 1;</code>
       */
      public Builder setRwSet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rwSet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rwSet = 1;</code>
       */
      public Builder clearRwSet() {
        
        rwSet_ = getDefaultInstance().getRwSet();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rwSet = 1;</code>
       */
      public Builder setRwSetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rwSet_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object businessData_ = "";
      /**
       * <code>optional string businessData = 2;</code>
       */
      public java.lang.String getBusinessData() {
        java.lang.Object ref = businessData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          businessData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string businessData = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBusinessDataBytes() {
        java.lang.Object ref = businessData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          businessData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string businessData = 2;</code>
       */
      public Builder setBusinessData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        businessData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string businessData = 2;</code>
       */
      public Builder clearBusinessData() {
        
        businessData_ = getDefaultInstance().getBusinessData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string businessData = 2;</code>
       */
      public Builder setBusinessDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        businessData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceResultJson_ = "";
      /**
       * <code>optional string serviceResultJson = 3;</code>
       */
      public java.lang.String getServiceResultJson() {
        java.lang.Object ref = serviceResultJson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceResultJson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceResultJson = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceResultJsonBytes() {
        java.lang.Object ref = serviceResultJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceResultJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceResultJson = 3;</code>
       */
      public Builder setServiceResultJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceResultJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceResultJson = 3;</code>
       */
      public Builder clearServiceResultJson() {
        
        serviceResultJson_ = getDefaultInstance().getServiceResultJson();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceResultJson = 3;</code>
       */
      public Builder setServiceResultJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceResultJson_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object oid_ = "";
      /**
       * <code>optional string oid = 4;</code>
       */
      public java.lang.String getOid() {
        java.lang.Object ref = oid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string oid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOidBytes() {
        java.lang.Object ref = oid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string oid = 4;</code>
       */
      public Builder setOid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string oid = 4;</code>
       */
      public Builder clearOid() {
        
        oid_ = getDefaultInstance().getOid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string oid = 4;</code>
       */
      public Builder setOidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.wfTransaction)
    }

    // @@protoc_insertion_point(class_scope:protos.wfTransaction)
    private static final org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction();
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<wfTransaction>
        PARSER = new com.google.protobuf.AbstractParser<wfTransaction>() {
      public wfTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new wfTransaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<wfTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<wfTransaction> getParserForType() {
      return PARSER;
    }

    public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface bigPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.bigPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> 
        getWfTransactionList();
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getWfTransaction(int index);
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    int getWfTransactionCount();
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder> 
        getWfTransactionOrBuilderList();
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder getWfTransactionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.bigPackage}
   */
  public  static final class bigPackage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.bigPackage)
      bigPackageOrBuilder {
    // Use bigPackage.newBuilder() to construct.
    private bigPackage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private bigPackage() {
      wfTransaction_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private bigPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                wfTransaction_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              wfTransaction_.add(
                  input.readMessage(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          wfTransaction_ = java.util.Collections.unmodifiableList(wfTransaction_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_bigPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_bigPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.class, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.Builder.class);
    }

    public static final int WFTRANSACTION_FIELD_NUMBER = 1;
    private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> wfTransaction_;
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> getWfTransactionList() {
      return wfTransaction_;
    }
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder> 
        getWfTransactionOrBuilderList() {
      return wfTransaction_;
    }
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    public int getWfTransactionCount() {
      return wfTransaction_.size();
    }
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getWfTransaction(int index) {
      return wfTransaction_.get(index);
    }
    /**
     * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
     */
    public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder getWfTransactionOrBuilder(
        int index) {
      return wfTransaction_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < wfTransaction_.size(); i++) {
        output.writeMessage(1, wfTransaction_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < wfTransaction_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, wfTransaction_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage)) {
        return super.equals(obj);
      }
      org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage other = (org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage) obj;

      boolean result = true;
      result = result && getWfTransactionList()
          .equals(other.getWfTransactionList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getWfTransactionCount() > 0) {
        hash = (37 * hash) + WFTRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getWfTransactionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.bigPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.bigPackage)
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_bigPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_bigPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.class, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.Builder.class);
      }

      // Construct using org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWfTransactionFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (wfTransactionBuilder_ == null) {
          wfTransaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          wfTransactionBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.internal_static_protos_bigPackage_descriptor;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage getDefaultInstanceForType() {
        return org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.getDefaultInstance();
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage build() {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage buildPartial() {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage result = new org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage(this);
        int from_bitField0_ = bitField0_;
        if (wfTransactionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            wfTransaction_ = java.util.Collections.unmodifiableList(wfTransaction_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.wfTransaction_ = wfTransaction_;
        } else {
          result.wfTransaction_ = wfTransactionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage) {
          return mergeFrom((org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage other) {
        if (other == org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage.getDefaultInstance()) return this;
        if (wfTransactionBuilder_ == null) {
          if (!other.wfTransaction_.isEmpty()) {
            if (wfTransaction_.isEmpty()) {
              wfTransaction_ = other.wfTransaction_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWfTransactionIsMutable();
              wfTransaction_.addAll(other.wfTransaction_);
            }
            onChanged();
          }
        } else {
          if (!other.wfTransaction_.isEmpty()) {
            if (wfTransactionBuilder_.isEmpty()) {
              wfTransactionBuilder_.dispose();
              wfTransactionBuilder_ = null;
              wfTransaction_ = other.wfTransaction_;
              bitField0_ = (bitField0_ & ~0x00000001);
              wfTransactionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWfTransactionFieldBuilder() : null;
            } else {
              wfTransactionBuilder_.addAllMessages(other.wfTransaction_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> wfTransaction_ =
        java.util.Collections.emptyList();
      private void ensureWfTransactionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          wfTransaction_ = new java.util.ArrayList<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction>(wfTransaction_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder> wfTransactionBuilder_;

      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> getWfTransactionList() {
        if (wfTransactionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wfTransaction_);
        } else {
          return wfTransactionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public int getWfTransactionCount() {
        if (wfTransactionBuilder_ == null) {
          return wfTransaction_.size();
        } else {
          return wfTransactionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction getWfTransaction(int index) {
        if (wfTransactionBuilder_ == null) {
          return wfTransaction_.get(index);
        } else {
          return wfTransactionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder setWfTransaction(
          int index, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction value) {
        if (wfTransactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWfTransactionIsMutable();
          wfTransaction_.set(index, value);
          onChanged();
        } else {
          wfTransactionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder setWfTransaction(
          int index, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder builderForValue) {
        if (wfTransactionBuilder_ == null) {
          ensureWfTransactionIsMutable();
          wfTransaction_.set(index, builderForValue.build());
          onChanged();
        } else {
          wfTransactionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder addWfTransaction(org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction value) {
        if (wfTransactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWfTransactionIsMutable();
          wfTransaction_.add(value);
          onChanged();
        } else {
          wfTransactionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder addWfTransaction(
          int index, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction value) {
        if (wfTransactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWfTransactionIsMutable();
          wfTransaction_.add(index, value);
          onChanged();
        } else {
          wfTransactionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder addWfTransaction(
          org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder builderForValue) {
        if (wfTransactionBuilder_ == null) {
          ensureWfTransactionIsMutable();
          wfTransaction_.add(builderForValue.build());
          onChanged();
        } else {
          wfTransactionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder addWfTransaction(
          int index, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder builderForValue) {
        if (wfTransactionBuilder_ == null) {
          ensureWfTransactionIsMutable();
          wfTransaction_.add(index, builderForValue.build());
          onChanged();
        } else {
          wfTransactionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder addAllWfTransaction(
          java.lang.Iterable<? extends org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction> values) {
        if (wfTransactionBuilder_ == null) {
          ensureWfTransactionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, wfTransaction_);
          onChanged();
        } else {
          wfTransactionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder clearWfTransaction() {
        if (wfTransactionBuilder_ == null) {
          wfTransaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          wfTransactionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public Builder removeWfTransaction(int index) {
        if (wfTransactionBuilder_ == null) {
          ensureWfTransactionIsMutable();
          wfTransaction_.remove(index);
          onChanged();
        } else {
          wfTransactionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder getWfTransactionBuilder(
          int index) {
        return getWfTransactionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder getWfTransactionOrBuilder(
          int index) {
        if (wfTransactionBuilder_ == null) {
          return wfTransaction_.get(index);  } else {
          return wfTransactionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public java.util.List<? extends org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder> 
           getWfTransactionOrBuilderList() {
        if (wfTransactionBuilder_ != null) {
          return wfTransactionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wfTransaction_);
        }
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder addWfTransactionBuilder() {
        return getWfTransactionFieldBuilder().addBuilder(
            org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder addWfTransactionBuilder(
          int index) {
        return getWfTransactionFieldBuilder().addBuilder(
            index, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.wfTransaction wfTransaction = 1;</code>
       */
      public java.util.List<org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder> 
           getWfTransactionBuilderList() {
        return getWfTransactionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder> 
          getWfTransactionFieldBuilder() {
        if (wfTransactionBuilder_ == null) {
          wfTransactionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransaction.Builder, org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.wfTransactionOrBuilder>(
                  wfTransaction_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          wfTransaction_ = null;
        }
        return wfTransactionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.bigPackage)
    }

    // @@protoc_insertion_point(class_scope:protos.bigPackage)
    private static final org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage();
    }

    public static org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<bigPackage>
        PARSER = new com.google.protobuf.AbstractParser<bigPackage>() {
      public bigPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new bigPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<bigPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<bigPackage> getParserForType() {
      return PARSER;
    }

    public org.activiti.engine.impl.db.workflowClass.proto.bigPackage.wfPackage.bigPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_wfTransaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_wfTransaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_bigPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_bigPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020bigPackage.proto\022\006protos\"\\\n\rwfTransact" +
      "ion\022\r\n\005rwSet\030\001 \001(\t\022\024\n\014businessData\030\002 \001(\t" +
      "\022\031\n\021serviceResultJson\030\003 \001(\t\022\013\n\003oid\030\004 \001(\t" +
      "\":\n\nbigPackage\022,\n\rwfTransaction\030\001 \003(\0132\025." +
      "protos.wfTransactionBG\n:org.activiti.eng" +
      "ine.impl.db.workflowClass.proto.bigPacka" +
      "geB\twfPackageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_wfTransaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_wfTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_wfTransaction_descriptor,
        new java.lang.String[] { "RwSet", "BusinessData", "ServiceResultJson", "Oid", });
    internal_static_protos_bigPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_bigPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_bigPackage_descriptor,
        new java.lang.String[] { "WfTransaction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
